[package]
name = "kma_rustlang_pest_2025_illia"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "parser prefab for uni"

[dependencies]
anyhow = "1.0.100"
pest = "2.8.3"
pest_derive = "2.8.3"
